apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: microservicio-policy
  namespace: paul
spec:
  podSelector:
    matchLabels:
      app: microservicio
  policyTypes:
    - Ingress
    - Egress
